name: pytest

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install development dependencies
        run: pip install -r dev-requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install self
        run: pip install -e .
      - name: Run tests
        run: pytest
    if: github.event_name != 'pull_request' || github.event.action == 'opened'
